// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Filter3D

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture3D<float4> Input;
RWTexture3D<float4> Result;

[numthreads(8,8,8)]
void Filter3D (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    Result[id.xyz] = float4(Input[id.xyz].xyz * Input[id.xyz].w + Result[id.xyz].xyz * Result[id.xyz].w, 1);
}
