// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel WeightedBlend2D

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Input;
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void WeightedBlend2D (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    float weight = Input[id.xy].w;
    Result[id.xy] = float4(weight * Input[id.xy].xyz + (1 - weight) * Result[id.xy].xyz, 1);
}
