// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Add2D

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Input;
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void Add2D (uint3 id : SV_DispatchThreadID)
{
    Result[id.xy] = float4(Input[id.xy].xyz * Input[id.xy].w + Result[id.xy].xyz * Result[id.xy].w, 1);
}
