// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

RWTexture3D<float4> volume;

float4 color;

[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    //uint width;
    //uint height;
    //uint depth;
    //volume.GetDimensions(width, height, depth);
    //float4 c = color * id.z / depth;
    //volume[id.xyz] = c;
    volume[id.xyz] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 1.0);
}
